---
language: python
python: "2.7"
before_install:
 - sudo apt-get update -qq
install:
  - pip install ansible>=1.6.0
script:
  # Prepare tests
  - echo localhost > inventory

  # Check syntax
  - ansible-playbook --syntax-check -i inventory test.yml

  # Run
  - ansible-playbook -i inventory test.yml --connection=local --check --sudo