---
  - name: reboot nodes
    shell: "sleep {{ reboot_delay_on }} && shutdown -r now '{{ reboot_desc }}'"
    async: 1
    poll: 0
    ignore_errors: "{{ reboot_ignore_errors }}"

  - name: wait for nodes
    local_action: wait_for
    args:
      host: "{{ inventory_hostname }}"
      port: "{{ ssh_port }}"
      state: started
      delay: "{{ reboot_come_back }}"
      timeout: "{{ reboot_timeout }}"